// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Identifier struct {
	Username    *string  `json:"username"`
	Phonenumber *float64 `json:"phonenumber"`
}

type LoginInput struct {
	Identifier *Identifier `json:"identifier"`
	Password   string      `json:"password"`
}

type User struct {
	ID          *string  `json:"ID"`
	Username    *string  `json:"username"`
	Phonenumber *float64 `json:"phonenumber"`
}

type UserInput struct {
	Username    string  `json:"username"`
	Phonenumber float64 `json:"phonenumber"`
	Password    string  `json:"password"`
}
