// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.1
// source: authorization/authorization.proto

package authorization

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AuthorizationClient is the client API for Authorization service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthorizationClient interface {
	CreateJWT(ctx context.Context, in *Createjwtinput, opts ...grpc.CallOption) (*Createjwtoutput, error)
	DeleteJWT(ctx context.Context, in *Deletejwtinput, opts ...grpc.CallOption) (*Deletejwtoutput, error)
	ValidateJWT(ctx context.Context, in *Validatejwtinput, opts ...grpc.CallOption) (*Validatejwtoutput, error)
}

type authorizationClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthorizationClient(cc grpc.ClientConnInterface) AuthorizationClient {
	return &authorizationClient{cc}
}

func (c *authorizationClient) CreateJWT(ctx context.Context, in *Createjwtinput, opts ...grpc.CallOption) (*Createjwtoutput, error) {
	out := new(Createjwtoutput)
	err := c.cc.Invoke(ctx, "/Authorization/CreateJWT", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorizationClient) DeleteJWT(ctx context.Context, in *Deletejwtinput, opts ...grpc.CallOption) (*Deletejwtoutput, error) {
	out := new(Deletejwtoutput)
	err := c.cc.Invoke(ctx, "/Authorization/DeleteJWT", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorizationClient) ValidateJWT(ctx context.Context, in *Validatejwtinput, opts ...grpc.CallOption) (*Validatejwtoutput, error) {
	out := new(Validatejwtoutput)
	err := c.cc.Invoke(ctx, "/Authorization/ValidateJWT", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthorizationServer is the server API for Authorization service.
// All implementations must embed UnimplementedAuthorizationServer
// for forward compatibility
type AuthorizationServer interface {
	CreateJWT(context.Context, *Createjwtinput) (*Createjwtoutput, error)
	DeleteJWT(context.Context, *Deletejwtinput) (*Deletejwtoutput, error)
	ValidateJWT(context.Context, *Validatejwtinput) (*Validatejwtoutput, error)
	mustEmbedUnimplementedAuthorizationServer()
}

// UnimplementedAuthorizationServer must be embedded to have forward compatible implementations.
type UnimplementedAuthorizationServer struct {
}

func (UnimplementedAuthorizationServer) CreateJWT(context.Context, *Createjwtinput) (*Createjwtoutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateJWT not implemented")
}
func (UnimplementedAuthorizationServer) DeleteJWT(context.Context, *Deletejwtinput) (*Deletejwtoutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteJWT not implemented")
}
func (UnimplementedAuthorizationServer) ValidateJWT(context.Context, *Validatejwtinput) (*Validatejwtoutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateJWT not implemented")
}
func (UnimplementedAuthorizationServer) mustEmbedUnimplementedAuthorizationServer() {}

// UnsafeAuthorizationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthorizationServer will
// result in compilation errors.
type UnsafeAuthorizationServer interface {
	mustEmbedUnimplementedAuthorizationServer()
}

func RegisterAuthorizationServer(s grpc.ServiceRegistrar, srv AuthorizationServer) {
	s.RegisterService(&Authorization_ServiceDesc, srv)
}

func _Authorization_CreateJWT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Createjwtinput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizationServer).CreateJWT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Authorization/CreateJWT",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizationServer).CreateJWT(ctx, req.(*Createjwtinput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authorization_DeleteJWT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Deletejwtinput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizationServer).DeleteJWT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Authorization/DeleteJWT",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizationServer).DeleteJWT(ctx, req.(*Deletejwtinput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authorization_ValidateJWT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Validatejwtinput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizationServer).ValidateJWT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Authorization/ValidateJWT",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizationServer).ValidateJWT(ctx, req.(*Validatejwtinput))
	}
	return interceptor(ctx, in, info, handler)
}

// Authorization_ServiceDesc is the grpc.ServiceDesc for Authorization service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Authorization_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Authorization",
	HandlerType: (*AuthorizationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateJWT",
			Handler:    _Authorization_CreateJWT_Handler,
		},
		{
			MethodName: "DeleteJWT",
			Handler:    _Authorization_DeleteJWT_Handler,
		},
		{
			MethodName: "ValidateJWT",
			Handler:    _Authorization_ValidateJWT_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "authorization/authorization.proto",
}
