// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.1
// source: authorization/authorization.proto

package authorization

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Createjwtinput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Userid string `protobuf:"bytes,1,opt,name=userid,proto3" json:"userid,omitempty"`
}

func (x *Createjwtinput) Reset() {
	*x = Createjwtinput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authorization_authorization_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Createjwtinput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Createjwtinput) ProtoMessage() {}

func (x *Createjwtinput) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_authorization_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Createjwtinput.ProtoReflect.Descriptor instead.
func (*Createjwtinput) Descriptor() ([]byte, []int) {
	return file_authorization_authorization_proto_rawDescGZIP(), []int{0}
}

func (x *Createjwtinput) GetUserid() string {
	if x != nil {
		return x.Userid
	}
	return ""
}

type Createjwtoutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *Createjwtoutput) Reset() {
	*x = Createjwtoutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authorization_authorization_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Createjwtoutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Createjwtoutput) ProtoMessage() {}

func (x *Createjwtoutput) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_authorization_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Createjwtoutput.ProtoReflect.Descriptor instead.
func (*Createjwtoutput) Descriptor() ([]byte, []int) {
	return file_authorization_authorization_proto_rawDescGZIP(), []int{1}
}

func (x *Createjwtoutput) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type Validatejwtinput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *Validatejwtinput) Reset() {
	*x = Validatejwtinput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authorization_authorization_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Validatejwtinput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Validatejwtinput) ProtoMessage() {}

func (x *Validatejwtinput) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_authorization_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Validatejwtinput.ProtoReflect.Descriptor instead.
func (*Validatejwtinput) Descriptor() ([]byte, []int) {
	return file_authorization_authorization_proto_rawDescGZIP(), []int{2}
}

func (x *Validatejwtinput) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type Validatejwtoutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Userid string `protobuf:"bytes,1,opt,name=userid,proto3" json:"userid,omitempty"`
}

func (x *Validatejwtoutput) Reset() {
	*x = Validatejwtoutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authorization_authorization_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Validatejwtoutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Validatejwtoutput) ProtoMessage() {}

func (x *Validatejwtoutput) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_authorization_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Validatejwtoutput.ProtoReflect.Descriptor instead.
func (*Validatejwtoutput) Descriptor() ([]byte, []int) {
	return file_authorization_authorization_proto_rawDescGZIP(), []int{3}
}

func (x *Validatejwtoutput) GetUserid() string {
	if x != nil {
		return x.Userid
	}
	return ""
}

type Deletejwtinput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Userid string `protobuf:"bytes,1,opt,name=userid,proto3" json:"userid,omitempty"`
}

func (x *Deletejwtinput) Reset() {
	*x = Deletejwtinput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authorization_authorization_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Deletejwtinput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deletejwtinput) ProtoMessage() {}

func (x *Deletejwtinput) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_authorization_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deletejwtinput.ProtoReflect.Descriptor instead.
func (*Deletejwtinput) Descriptor() ([]byte, []int) {
	return file_authorization_authorization_proto_rawDescGZIP(), []int{4}
}

func (x *Deletejwtinput) GetUserid() string {
	if x != nil {
		return x.Userid
	}
	return ""
}

type Deletejwtoutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res bool `protobuf:"varint,1,opt,name=res,proto3" json:"res,omitempty"`
}

func (x *Deletejwtoutput) Reset() {
	*x = Deletejwtoutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authorization_authorization_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Deletejwtoutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deletejwtoutput) ProtoMessage() {}

func (x *Deletejwtoutput) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_authorization_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deletejwtoutput.ProtoReflect.Descriptor instead.
func (*Deletejwtoutput) Descriptor() ([]byte, []int) {
	return file_authorization_authorization_proto_rawDescGZIP(), []int{5}
}

func (x *Deletejwtoutput) GetRes() bool {
	if x != nil {
		return x.Res
	}
	return false
}

var File_authorization_authorization_proto protoreflect.FileDescriptor

var file_authorization_authorization_proto_rawDesc = []byte{
	0x0a, 0x21, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f,
	0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x28, 0x0a, 0x0e, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x6a, 0x77, 0x74,
	0x69, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x22, 0x27, 0x0a,
	0x0f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x6a, 0x77, 0x74, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x28, 0x0a, 0x10, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x65, 0x6a, 0x77, 0x74, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x22, 0x2b, 0x0a, 0x11, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x6a, 0x77, 0x74, 0x6f,
	0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x22, 0x28, 0x0a,
	0x0e, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x6a, 0x77, 0x74, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x22, 0x23, 0x0a, 0x0f, 0x64, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x6a, 0x77, 0x74, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x72, 0x65, 0x73, 0x32, 0xab, 0x01, 0x0a,
	0x0d, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x30,
	0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4a, 0x57, 0x54, 0x12, 0x0f, 0x2e, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x6a, 0x77, 0x74, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x10, 0x2e, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x6a, 0x77, 0x74, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22, 0x00,
	0x12, 0x30, 0x0a, 0x09, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4a, 0x57, 0x54, 0x12, 0x0f, 0x2e,
	0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x6a, 0x77, 0x74, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x10,
	0x2e, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x6a, 0x77, 0x74, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74,
	0x22, 0x00, 0x12, 0x36, 0x0a, 0x0b, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x4a, 0x57,
	0x54, 0x12, 0x11, 0x2e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x6a, 0x77, 0x74, 0x69,
	0x6e, 0x70, 0x75, 0x74, 0x1a, 0x12, 0x2e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x6a,
	0x77, 0x74, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22, 0x00, 0x42, 0x11, 0x5a, 0x0f, 0x2e, 0x2f,
	0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_authorization_authorization_proto_rawDescOnce sync.Once
	file_authorization_authorization_proto_rawDescData = file_authorization_authorization_proto_rawDesc
)

func file_authorization_authorization_proto_rawDescGZIP() []byte {
	file_authorization_authorization_proto_rawDescOnce.Do(func() {
		file_authorization_authorization_proto_rawDescData = protoimpl.X.CompressGZIP(file_authorization_authorization_proto_rawDescData)
	})
	return file_authorization_authorization_proto_rawDescData
}

var file_authorization_authorization_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_authorization_authorization_proto_goTypes = []interface{}{
	(*Createjwtinput)(nil),    // 0: createjwtinput
	(*Createjwtoutput)(nil),   // 1: createjwtoutput
	(*Validatejwtinput)(nil),  // 2: validatejwtinput
	(*Validatejwtoutput)(nil), // 3: validatejwtoutput
	(*Deletejwtinput)(nil),    // 4: deletejwtinput
	(*Deletejwtoutput)(nil),   // 5: deletejwtoutput
}
var file_authorization_authorization_proto_depIdxs = []int32{
	0, // 0: Authorization.CreateJWT:input_type -> createjwtinput
	4, // 1: Authorization.DeleteJWT:input_type -> deletejwtinput
	2, // 2: Authorization.ValidateJWT:input_type -> validatejwtinput
	1, // 3: Authorization.CreateJWT:output_type -> createjwtoutput
	5, // 4: Authorization.DeleteJWT:output_type -> deletejwtoutput
	3, // 5: Authorization.ValidateJWT:output_type -> validatejwtoutput
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_authorization_authorization_proto_init() }
func file_authorization_authorization_proto_init() {
	if File_authorization_authorization_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_authorization_authorization_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Createjwtinput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authorization_authorization_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Createjwtoutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authorization_authorization_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Validatejwtinput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authorization_authorization_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Validatejwtoutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authorization_authorization_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Deletejwtinput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authorization_authorization_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Deletejwtoutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_authorization_authorization_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_authorization_authorization_proto_goTypes,
		DependencyIndexes: file_authorization_authorization_proto_depIdxs,
		MessageInfos:      file_authorization_authorization_proto_msgTypes,
	}.Build()
	File_authorization_authorization_proto = out.File
	file_authorization_authorization_proto_rawDesc = nil
	file_authorization_authorization_proto_goTypes = nil
	file_authorization_authorization_proto_depIdxs = nil
}
